
name: Build docker image on release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v3
      with:
        python-version: "3.14"
    - run: pip install pytest coverage Flask-SQLAlchemy
    - run: PYTHONPATH=src 
    - run: pytest

    - run: docker build -t therecipebox .
    - run: docker save therecipebox -o therecipebox.tar
    - run: zip therecipebox-image.zip therecipebox.tar
    - uses: actions/upload-artifact@v4
      with: 
        name: therecipebox_${GITHUB_REF_NAME}
        path: therecipebox-image.zip